### ISSUE TITLE
Suggestion: Overlay graphlet of hashrates

### ISSUE THREAD

**Issue by indyramp** [jouir/mining-dashboards#1]
I see there are separate graphs for the effective, reported, and daily hashrates. 

I think it would be cool to have a graph that overlays all three.

Since they are usually (mostly) all in the same range, a linear graph might not be as useful, so I suggest a logarithmic graph so that (for example) with a miner whose range is usually 350-400, their graph wouldn't be mostly the common 0-350 range. Would be easier to recognize and understand as averages converge.

**Comment by jouir** [comment]
Graphs have been merged together. The Y-min is now set to "auto" to focus on the little differences instead of "0".

For the logarithmic scale, it is possible but we have multiple base available: 2, 10, 32, 1024.

Log2:
![base2](https://user-images.githubusercontent.com/24910974/111623032-28b54f00-87ea-11eb-97fb-fca4650762b6.png)

Log10:
![base10](https://user-images.githubusercontent.com/24910974/111623033-294de580-87ea-11eb-82a0-cda66823effd.png)

Log32:
![base32](https://user-images.githubusercontent.com/24910974/111623034-294de580-87ea-11eb-9a0e-fc3721f6f920.png)

Log1024:
![base1024](https://user-images.githubusercontent.com/24910974/111623036-29e67c00-87ea-11eb-98f5-3bf2c77787ff.png)

Linear:
![linear](https://user-images.githubusercontent.com/24910974/111623037-29e67c00-87ea-11eb-82fd-7802724587d8.png)

What is the best option to you?

**Comment by indyramp** [comment]
With the auto-scale, I think log scale may not be necessary. I like LInear and Log2 of the choices given though. Thanks!

**Comment by jouir** [comment]
Let's go for the linear scale. If you change your mind, feel free to re-open this issue.
