### ISSUE TITLE
Chia Daily revenue and Monthly revenue not correct in dashbord for Miner

### ISSUE THREAD

**Issue by ebeng** [jouir/mining-dashboards#9]
`SELECT sum(balance_increase)/1000000000000000000 FROM (select non_negative_difference("balance") AS balance_increase FROM "flexpool_miner_balance" WHERE "miner" =~ /^$miner$/ AND "coin" = 'eth' AND $timeFilter) GROUP BY time(1d) TZ('$timezone');`

The code is still pointing to eth where the definition is set to XCH on the top of the page of the dashboards for some of the panels. 

![image](https://user-images.githubusercontent.com/19037120/130255736-f6d2244b-ff6f-4b54-91c7-a86aa732b9e3.png)

**Comment by jouir** [comment]
On daily revenue panel, there are 4 queries to InfluxDB:

![Screenshot from 2021-08-20 17-29-54](https://user-images.githubusercontent.com/24910974/130257137-742f1afb-55cd-4813-a9f5-51f1fd75d6dd.png)

Query A returns the daily revenue for `coin=eth`. In your case, no point will be returned. You won't see the `revenue (ETH)` line on the graph.
Query B returns the daily revenue for `coin=eth` converted to fiat. Same as A, no point will be returned.
Query C returns the daily revenue for `coin=xch`. In your case, points will be returned so you'll see the `revenue (XCH)` line on the graph.
Query D returns the daily revenue for `coin=xch` converted to fiat. Same as C, you'll see the `revenue (fiat)` line based on your Chia earnings.

Same for monthly revenue and lots of other panels.

Multiple queries are required because:
* units are different (`ETH` or `XCH`)
* values returned by the Flexpool API use the smallest unit of the coin (1 XCH = 1,000,000 mojo, 1 ETH = 1,000,000,000,000,000,000 wei)

**Comment by jouir** [comment]
Unfortunately, [Flexpool](https://www.reddit.com/r/Flexpool/comments/16q72ul/action_required_flexpoolio_shutdown_notice_nov_1/) has shut down so I can't reproduce.
